### ISSUE TITLE
Where is lat and long set from ?

### ISSUE THREAD

**Issue by harikt** [MicahCarrick/PHP-ZipCode-Class#1]
Hi , 

I have a doubt. Wondering how the $lat and $lon are set .

Is it missing ?

**Comment by ketanthaker** [comment]
Hi harikt,

$lan and $lon are being set from the DB using these functions:

Line # 342: private function setPropertiesFromDb()
Line # 328: private function setPropertiesFromArray($a)

Based on the given zipcode/inputs it finds $lat, $lon and other required info from the DB > zip_code table.
